import "../../styles/globals.css";
import "@mantine/core/styles.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "./providers/Providers";
import { ColorSchemeScript, createTheme, MantineProvider } from "@mantine/core";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  const theme = createTheme({

  });
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <ColorSchemeScript defaultColorScheme="light" />
          <MantineProvider theme={theme} defaultColorScheme="light">{children}</MantineProvider>
        </Providers>
      </body>
    </html>
  );
}
